version: 2.1
commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

executors:
  linux-8-jdk:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    parameters:
      os:
        type: executor

    executor: << parameters.os >>

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - spark-redis-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline 

      - save_cache:
          paths:
            - ~/.m2
          key: spark-redis-{{ checksum "pom.xml" }}

      - run: 
          name: install Redis
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:redislabs/redis
            sudo apt-get update
            sudo apt-get install -y redis 

      - run: make test
      
      - run:
          name: switch scala to 2.12 
          command: |
            sleep 5s # let redis exit gracefully (we use kill, not kill -9 in makefile)
            ps aux | grep redis
            ./dev/change-scala-version.sh 2.12 # switch to scala 2.12
      
      - run: 
          name: test with scala 2.12     
          command: make test
      
      - early_return_for_forked_pull_requests

      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} 
     
      - run: mvn -s .circleci.settings.xml -DskipTests deploy

workflows:
  all-jdks:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux-8-jdk]
